name: Danger CI Test

on:
  pull_request:

jobs:
  build:
    name: Build and XCTest
    runs-on: self-hosted 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Danger CI Test
        run: |
         xcodebuild build -project swiftUI_XCUITest.xcodeproj -scheme swiftUI_XCUITest -destination "id=B7C1A209-ACF8-4012-BB21-14B7CDBD3808"
      - name: Danger CI Test
        run: |
         brew install danger/tap/danger-swift
         # Run danger
         danger-swift ci

      #- name: Danger JS
      #  uses: danger/danger-js@X.Y.Z
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
